server:
  port: 23853
  servlet:
    context-path: /api

spring:
  application:
    name: aether-executor

aether:
  server:
    host: localhost:23843
    context-path: /api
  client:
    #name: executor1
    #host: localhost:8082
