server:
  port: 23843
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb://ds:123456@ds.com:27017/ds
  #Redis 配置
  redis:
    # Redis服务器地址
    host: ds.com
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 链接超时时间 单位 ms（毫秒）
    timeout: 3000
    # Redis 线程池设置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 3000
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  # 邮件
  mail:
    host: smtp.qq.com
    port: 465
    username: doson1996@vip.qq.com
    password: ogbnzaalwfwbgchh
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

aether:
  server:
    executor:
      selector:
        type: poll
    scheduler:
        type: distributedCronScheduler
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show:
        details: always