server:
  port: 8081
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb://ds:123456@ds.com:27017/ds
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

aether:
  server:
    executor:
      selector:
        type: poll

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show:
        details: always