server:
  port: 8081
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb://ds:123456@ds.com:27017/ds

aether:
  server:
    executor:
      selector:
        type: poll
